// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: badges.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createBadge = `-- name: CreateBadge :one
INSERT INTO badges (
    token_hash,
    subject,
    status,
    color,
    style
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, token_hash, subject, status, color, style, created_at, updated_at
`

type CreateBadgeParams struct {
	TokenHash string `json:"token_hash"`
	Subject   string `json:"subject"`
	Status    string `json:"status"`
	Color     string `json:"color"`
	Style     string `json:"style"`
}

func (q *Queries) CreateBadge(ctx context.Context, arg CreateBadgeParams) (Badge, error) {
	row := q.db.QueryRowContext(ctx, createBadge,
		arg.TokenHash,
		arg.Subject,
		arg.Status,
		arg.Color,
		arg.Style,
	)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Subject,
		&i.Status,
		&i.Color,
		&i.Style,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBadge = `-- name: DeleteBadge :exec
DELETE FROM badges
WHERE id = $1
`

func (q *Queries) DeleteBadge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBadge, id)
	return err
}

const getBadgeByID = `-- name: GetBadgeByID :one
SELECT id, token_hash, subject, status, color, style, created_at, updated_at
FROM badges
WHERE id = $1
`

func (q *Queries) GetBadgeByID(ctx context.Context, id uuid.UUID) (Badge, error) {
	row := q.db.QueryRowContext(ctx, getBadgeByID, id)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Subject,
		&i.Status,
		&i.Color,
		&i.Style,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBadge = `-- name: UpdateBadge :one
UPDATE badges
SET subject = $2,
    status = $3,
    color = $4,
    style = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, token_hash, subject, status, color, style, created_at, updated_at
`

type UpdateBadgeParams struct {
	ID      uuid.UUID `json:"id"`
	Subject string    `json:"subject"`
	Status  string    `json:"status"`
	Color   string    `json:"color"`
	Style   string    `json:"style"`
}

func (q *Queries) UpdateBadge(ctx context.Context, arg UpdateBadgeParams) (Badge, error) {
	row := q.db.QueryRowContext(ctx, updateBadge,
		arg.ID,
		arg.Subject,
		arg.Status,
		arg.Color,
		arg.Style,
	)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Subject,
		&i.Status,
		&i.Color,
		&i.Style,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
