// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBadge(ctx context.Context, arg CreateBadgeParams) (Badge, error)
	DeleteBadge(ctx context.Context, id uuid.UUID) error
	GetBadgeByID(ctx context.Context, id uuid.UUID) (Badge, error)
	UpdateBadge(ctx context.Context, arg UpdateBadgeParams) (Badge, error)
}

var _ Querier = (*Queries)(nil)
